#!/bin/sh
set -e

# If the user didn't explicitly set NODE_EXTRA_CA_CERTS, try to auto-detect
# the repo's corporate CA bundle (generated by scripts/setup-node-extra-ca.ps1).
if [ -z "${NODE_EXTRA_CA_CERTS:-}" ]; then
  for candidate in \
    "/app/.certs/corp-windows-store.pem" \
    "/app/.certs/corp-chain.pem" \
    "/app/.certs/corp-bundle.pem" \
    "/app/.certs/corp-root.pem"; do
    if [ -f "$candidate" ]; then
      export NODE_EXTRA_CA_CERTS="$candidate"
      echo "[docker] Using NODE_EXTRA_CA_CERTS=$candidate"
      break
    fi
  done
fi

exec "$@"
