
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Avoid throwing during config module load when DATABASE_URL isn't set.
    // (Vercel build env can be missing/misconfigured; build script will provide a fallback for `prisma generate`.)
    url: databaseUrl ?? "",
  },
});
